//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DEBUG368.RC
//
#define IDD_MAIN                        101
#define IDI_ICON                        102
#define IDD_I2C_PROGRAM                 103
#define IDD_HELP                        105
#define IDD_PUWIDTH                     107
#define IDC_EDTDLLVER                   1009
#define IDC_EDTDEVVER                   1010
#define IDC_OPEN                        1011
#define IDC_CLOSE                       1012
#define IDC_DESCRIPTION                 1013
#define IDC_BTNIO                       1014
#define IDC_BTNCONBYTE                  1015
#define IDC_RADCONBYTEWRITE             1016
#define IDC_RADCONBYTEREAD              1017
#define IDC_EXIT                        1021
#define IDC_EDTINTLINE                  1022
#define IDC_EDTBASEADDR                 1023
#define IDC_EDTMEM                      1024
#define IDC_BTNMEM                      1025
#define IDC_EDTMEMADDR                  1026
#define IDC_RADMEMBYTE                  1027
#define IDC_RADMEMDWORD                 1028
#define IDC_RADMEMREAD                  1029
#define IDC_RADMEMWRITE                 1030
#define IDC_EDTMEMDATA                  1031
#define IDC_STATUS                      1035
#define IDC_RADI2CREAD                  1036
#define IDC_RADI2CWRITE                 1037
#define IDC_EDTDEVADDR                  1038
#define IDC_EDTDATADDR                  1039
#define IDC_BTNI2C                      1040
#define IDC_EDTI2CDATA                  1041
#define IDC_BTNI2C_PROGRAM              1042
#define IDC_VID                         1048
#define IDC_DID                         1049
#define IDC_RID                         1050
#define IDC_SVID                        1051
#define IDC_SID                         1052
#define IDC_PROGRAM                     1053
#define IDC_PROGRAM_EXIT                1054
#define IDC_PROMREAD                    1054
#define IDC_SPI                         1055
#define IDC_SPI_31                      1056
#define IDC_SPI_15                      1057
#define IDC_SPI3                        1058
#define IDC_SPI4                        1059
#define IDC_SPI_SET                     1060
#define IDC_FLASH_WRITE                 1061
#define IDC_FLASH_ERASE                 1062
#define IDC_FLASH_EXIT                  1063
#define IDC_FLASH_READ                  1064
#define IDC_FLASH_LOADFILE              1065
#define IDC_FILE                        1066
#define IDC_COMBO_IRQ_TYPE              1068
#define IDC_COMBO_IRQ_POLARITY          1069
#define IDC_IRQ_SET                     1070
#define IDC_IRQ_TEST                    1071
#define IDC_EDIT_IRQ                    1072
#define IDC_EDITINT1                    1072
#define IDC_DEVICE_NUMBER               1074
#define IDC_EDIT_HELP                   1075
#define IDC_PUWIDTH                     1089
#define IDC_CBPU                        1090
#define IDC_PULSHOW                     1092
#define IDC_STATIC1                     1093
#define IDC_BTNPU                       1094
#define IDC_EDIT_IRQ1                   1095
#define IDC_IRQ_TEST1                   1096
#define IDC_CBIOMODEL                   1107
#define IDC_CBIOADDTYPE                 1109
#define IDC_EDITIOADD                   1110
#define IDC_EDIT10                      1111
#define IDC_EDITIOLEN                   1111
#define IDC_BTNIORD                     1112
#define IDC_BTNIOWR                     1113
#define IDC_BTNMEMRD                    1114
#define IDC_BTNMEMWR                    1115
#define IDC_BTNSPIRD                    1116
#define IDC_BTNSPIWR                    1117
#define IDC_EDITI2CADD                  1119
#define IDC_BTNI2CRD                    1120
#define IDC_BTNI2CWR                    1121
#define IDC_EDITI2CDATA                 1122
#define IDC_CBSPINUM                    1127
#define IDC_CBSPICLK                    1128
#define IDC_BTNSPISET                   1129
#define IDC_EDITCONADD                  1131
#define IDC_EDITCONDATA                 1132
#define IDC_BTNCONRD                    1133
#define IDC_BTNCONWR                    1134
#define IDC_BTNCLOSE                    1139
#define IDC_BTNOPEN                     1140
#define IDC_BTNHELP                     1141
#define IDC_BTNEXIT                     1142
#define IDC_BTNINT1                     1144
#define IDC_EDITINT2                    1145
#define IDC_BTNINT2                     1146
#define IDC_CBMEMMODEL                  1148
#define IDC_EDITMEMADD                  1149
#define IDC_EDITMEMLEN                  1150
#define IDC_BUTTON23                    1153
#define IDC_CB32                        1156
#define IDC_EDITIODATA                  1157
#define IDC_BTNIOCL                     1158
#define IDC_EDITMEMDATA                 1159
#define IDC_BTNMEMCL                    1160
#define IDC_EDITSPIDATA                 1161
#define IDC_BUTTON28                    1162
#define IDC_BTNSPICL                    1162
#define IDC_EDITSPILEN                  1163
#define IDC_EDIT                        1164
#define IDC_STATICMEM                   1167
#define IDC_EDITFLASH                   1168
#define IDC_STATICI2C                   1169

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1170
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
